/* eslint-disable no-undef */
describe('Admin can', () => {
    it('change contact data and save', () => {
        cy.visit('/login')
        cy.url().should('eq', 'http://localhost:3000/login')
        cy.get('.btn')
            .click()
        cy.url().should('eq', 'http://localhost:3000/customers')
        cy.get('tbody > :nth-child(1) > :nth-child(1)').click()
        cy.url().should('eq', 'http://localhost:3000/customers/1')
        cy.get('div[name="address"] > .cornered').clear().type("Neue Strasse 20")
        cy.get('div[name="email"] > .cornered').clear().type("neue@email.ch")
        cy.get('.row > :nth-child(2) > .btn-container > .btn').click()
        expect(cy.get('.fade').should("have.text", "Kontaktdaten wurden erfolgreich gespeichert"))

    })
    it('change personal data and save', () => {
        cy.visit('/login')
        cy.url().should('eq', 'http://localhost:3000/login')
        cy.get('.btn')
            .click()
        cy.url().should('eq', 'http://localhost:3000/customers')
        cy.get('tbody > :nth-child(1) > :nth-child(1)').click()
        cy.url().should('eq', 'http://localhost:3000/customers/1')
        cy.get('div[name="firstName"] > .cornered').clear().type("VornameTest")
        cy.get('div[name="lastName"] > .cornered').clear().type("NachnameTest")
        cy.get('.section-light > .btn-container > .btn').click()
        expect(cy.get('.fade').should("have.text", "Persönliche Daten wurden erfolgreich gespeichert"))

    })
    it('see an error message on save if a field is invalid', () => {
        cy.visit('/login')
        cy.url().should('eq', 'http://localhost:3000/login')
        cy.get('.btn')
            .click()
        cy.url().should('eq', 'http://localhost:3000/customers')
        cy.get('tbody > :nth-child(1) > :nth-child(1)').click()
        cy.url().should('eq', 'http://localhost:3000/customers/1')
        cy.get('div[name="firstName"] > .cornered').clear()
        cy.get('div[name="lastName"] > .cornered').clear()
        cy.get('.row > :nth-child(2) > :nth-child(6)').click()
        expect(cy.get('div[name="firstName"] > .invalid-feedback').should("have.text", "Dieses Feld wird benötigt"))
        expect(cy.get('div[name="lastName"] > .invalid-feedback').should("have.text", "Dieses Feld wird benötigt"))
    })
})